networks:
  proxy:
    external: true

services:
  traefik:
    image: traefik:v3.1
    restart: unless-stopped
    command: ["sh", "-c", "chmod +x /start-traefik.sh && /start-traefik.sh"]
    environment:
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - LETSENCRYPT_STAGING=${LETSENCRYPT_STAGING:-false}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic:/etc/traefik/dynamic:ro
      - ./letsencrypt:/letsencrypt
      - ./start-traefik.sh:/start-traefik.sh:ro
    networks:
      - proxy
