log:
  level: WARN

accessLog: {}

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  le:
    acme:
      email: "${LETSENCRYPT_EMAIL}"
      storage: /letsencrypt/acme.json
      # Toggle staging by setting LETSENCRYPT_STAGING=true in .env
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      tlsChallenge: {}
